---
title: "Data_Production"
format: html
editor_options: 
  chunk_output_type: console
---

```{r}

source("~/Documents/Coding/Website/biostatistics/00 Functions/Functions.R")

clean_up()

if(!require(pharmaverse)){install.packages("pharmaverse"); library(pharmaverse)}
if(!require(tidyverse)){install.packages("tidyverse"); library(tidyverse)}
if(!require(pharmaverse)){install.packages("pharmaverse"); library(pharmaverse)}
if(!require(pharmaverseadam)){install.packages("pharmaverseadam"); library(pharmaverseadam)}
if(!require(gtsummary)){install.packages("gtsummary"); library(gtsummary)}
if(!require(gt)){install.packages("gt"); library(gt)}  # also contains OfficeR
if(!require(remotes)){install.packages("remotes"); library(remotes)}
if (!require(cardinal)) {remotes::install_github("pharmaverse/cardinal"); library(cardinal)}
if(!require(random.cdisc.data)){install.packages("random.cdisc.data"); library(random.cdisc.data)}
if(!require(kableExtra)){install.packages("kableExtra"); library(kableExtra)}


wd = "~/Documents/Coding/Website/biostatistics/Data"


```

```{r, generate the R data}

adsl <- random.cdisc.data::cadsl
advs <- random.cdisc.data::cadvs
adtte <- random.cdisc.data::cadtte
adae <- random.cdisc.data::cadae


#Save Original Data just in case
save.image(paste0(wd, "/Data.RDS"))

```


```{r, data wrangling adsl }
#| warning: false
#| echo: false

# Take some variables ADVS so you make some subgroups - because why not?

advs <- advs %>%
  filter(AVISIT == "BASELINE", PARAMCD %in% c("WEIGHT", "SYSBP", "DIABP")) |> 
  select(USUBJID, PARAMCD, AVAL) |> 
  pivot_wider(names_from = PARAMCD,  values_from = AVAL)

adsl <- left_join(adsl, advs, by = "USUBJID")

#Nicer drug names
adsl <- adsl |> 
  select(- c(TRT02P, TRT02A)) |> 
  mutate(TRT01P = case_when(
    TRT01P == "A: Drug X" ~ "Fakemethaline 50 mg",
    TRT01P == "C: Combination" ~ "Fakemethaline 150 mg",
    TRT01P == "B: Placebo" ~ "Placebo"),
    TRT01A = case_when(
      TRT01A == "A: Drug X" ~ "Fakemethaline 50 mg",
      TRT01A == "C: Combination" ~ "Fakemethaline 150 mg",
      TRT01A == "B: Placebo" ~ "Placebo"),
    AGEGRP1  = as.factor(case_when(
      AGE >= 17 & AGE < 65 ~ "≥17 to <65",
      AGE >= 65 ~ "≥65",
      AGE >= 65 & AGE < 75 ~ "≥65 to &lt;75",
      AGE >= 75 ~ "≥75")),
    SEX = as.factor(case_when(
      SEX == "F" ~ "Female",
      SEX == "M" ~ "Male")),
    HIGHBP = as.factor(case_when(
      SYSBP >= 130 & DIABP  >= 80 ~ "Yes",
      TRUE ~ "No")),
    OVER80KG = as.factor(case_when(
      WEIGHT >= 80 ~ "Yes",
      TRUE ~ "No")),
    RACE_BLACK = as.factor(case_when(
      RACE == "BLACK OR AFRICAN AMERICAN" ~ "Yes",
      TRUE ~ "No"
    )),
    RACE = str_to_title(RACE),
    ETHNIC = str_to_title(ETHNIC))


```


```{r, data wrangling adtte}
#| warning: false
#| echo: false

Patients <- adsl %>% 
  select(SUBJID, TRT01P, TRT01A, HIGHBP, OVER80KG)

adtte <- adtte %>%
  mutate(TRT01P = case_when(
    TRT01P == "A: Drug X" ~ "Fakemethaline 50 mg",
    TRT01P == "C: Combination" ~ "Fakemethaline 150 mg",
    TRT01P == "B: Placebo" ~ "Placebo"),
    TRT01A = case_when(
      TRT01A == "A: Drug X" ~ "Fakemethaline 50 mg",
      TRT01A == "C: Combination" ~ "Fakemethaline 150 mg",
      TRT01A == "B: Placebo" ~ "Placebo")) %>% 
  left_join(Patients , adtte, by = c("SUBJID", "TRT01P", "TRT01A")) %>% 
  mutate(AGEGRP1  = as.factor(case_when(
      AGE >= 17 & AGE < 65 ~ "≥17 to <65",
      AGE >= 65 ~ "≥65",
      AGE >= 65 & AGE < 75 ~ "≥65 to &lt;75",
      AGE >= 75 ~ "≥75")),
    SEX = as.factor(case_when(
      SEX == "F" ~ "Female",
      SEX == "M" ~ "Male")),
    RACE_BLACK = as.factor(case_when(
      RACE == "BLACK OR AFRICAN AMERICAN" ~ "Yes",
      TRUE ~ "No"
    )),
    RACE = str_to_title(RACE),
    ETHNIC = str_to_title(ETHNIC))


```

```{r, data wrangling adtte}

adae <- adae %>%
  mutate(TRT01P = case_when(
    TRT01P == "A: Drug X" ~ "Fakemethaline 50 mg",
    TRT01P == "C: Combination" ~ "Fakemethaline 150 mg",
    TRT01P == "B: Placebo" ~ "Placebo"),
    TRT01A = case_when(
      TRT01A == "A: Drug X" ~ "Fakemethaline 50 mg",
      TRT01A == "C: Combination" ~ "Fakemethaline 150 mg",
      TRT01A == "B: Placebo" ~ "Placebo")) %>% 
  left_join(Patients , adtte, by = c("SUBJID", "TRT01P", "TRT01A")) %>% 
  mutate(AGEGRP1  = as.factor(case_when(
      AGE >= 17 & AGE < 65 ~ "≥17 to <65",
      AGE >= 65 ~ "≥65",
      AGE >= 65 & AGE < 75 ~ "≥65 to &lt;75",
      AGE >= 75 ~ "≥75")),
    SEX = as.factor(case_when(
      SEX == "F" ~ "Female",
      SEX == "M" ~ "Male")),
    RACE_BLACK = as.factor(case_when(
      RACE == "BLACK OR AFRICAN AMERICAN" ~ "Yes",
      TRUE ~ "No"
    )),
    RACE = str_to_title(RACE),
    ETHNIC = str_to_title(ETHNIC))


save.image(paste0(wd, "/Data_Processed.RDS"))
```